config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  resource :session, only: [:new, :create, :destroy]
  resources :categories
  resources :terms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/term.rb
class Term < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #returns user if logged in
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  #returns boolean if logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def authorize!
    redirect_to login_path unless logged_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :subject)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]

    user = User.find_by(email: email)

    if user && user.authenticate(password)
      session[:user_id] = user.id

      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_filter :authorize!
  def index
    @terms = Term.all
  end

  def show
    @term = Term.find(params[:id])
  end

  def new
    @term = Term.new
  end

  def edit
    @term = Term.find(params[:id])
  end

  def create
    # to investigate that is being sent
    # render plain: params[:term].inspect
    @term = Term.new(term_params)

    if @term.save
      redirect_to @term
    else
      render 'new'
    end
  end

  def update
    @term = Term.find(params[:id])

    if @term.update(term_params)
      redirect_to @term
    else
      render 'edit'
    end
  end


  # def update
  #   @article = Article.find(params[:id])
  #
  #   if @article.update(article_params)
  #     redirect_to @article
  #   else
  #     render 'edit'
  #   end
  # end

  def destroy
    @term = Term.find(params[:id])
    @term.destroy

    redirect_to terms_path
  end

  private
    def term_params
      params.require(:term).permit(:name, :definition, :author, :web_link, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to signup_path
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  # to be added to appropriate files
  before_filter :authorize!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :subject
    = f.text_field :subject
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table.table.table-striped.table-hover
  %thead
    %tr
      %th Name
      %th Subject
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.subject
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path
\|
=link_to 'Home', root_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Subject:
  = @category.subject

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path
\|
=link_to 'Home'

app/views/homepage/index.html.haml
%h1 Welcome to TIY Database

%p
  = link_to 'Login', login_path
  %br
  =link_to 'See Terms', terms_path
  %br
  =link_to 'See Categories', categories_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TiyRailsGlossary
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  .navbar
    .container
      .col-md-8
        %a
          =root_path
          %image(src="logo-white.png")

      .col-md-4
        - if logged_in?
          Logged in:
          =current_user.name
          \|
          = link_to "Log Out", logout_path
        - else
          =link_to "Login", login_path
          \|
          =link_to "Signup", signup_path
  .container
    = yield

app/views/session/new.html.haml
%h1 login

= form_tag login_path do
  Email:
  = text_field_tag :email
  %br
  Password:
  = password_field_tag :password
  %br
  =submit_tag "Submit"

app/views/terms/_form.html.haml
= form_for(@term) do |f|
  -if @term.errors.any?
    #error_explanation
      %h2
        = pluralize(@term.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - @term.errors.full_messages.each do |msg|
          %li
          =msg
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :definition
    %br
    = f.text_field :definition
  %p
    = f.label :author
    %br
    = f.text_field :author
  %p
    =f.label :web_link
    %br
    = f.text_field :web_link
  %p
    =f.label :category_id
    %br
    =f.text_field :category_id
  %p
    =f.submit

app/views/terms/edit.html.haml
%h1 Edit Article

= render 'form', term: @term 

= link_to 'Back', terms_path

app/views/terms/index.html.haml
%h1 Terms
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Name
      %th Definition
      %th Author
      %th Category
      %th Web link
      %th{:colspan => "3"}
  %tbody
    - @terms.each do |term|
      %tr
        %td= term.name
        %td= term.definition
        %td= term.author
        %td= term.category_id
        %td= term.web_link
        %td= link_to 'Show', term
        %td= link_to 'Edit', edit_term_path(term)
        %td= link_to 'Destroy', term_path(term),
                                method: :delete,
                                data: { confirm: 'Are you sure?'}
%br/
= link_to 'New Term', new_term_path
\|
=link_to 'Home', root_path

app/views/terms/new.html.haml
%h1 New Term

=render 'form'

=link_to 'Back', terms_path

app/views/terms/show.html.haml
%p
  Name:
  = @term.name
%p
  Definition:
  =@term.definition
%p
  Author:
  =@term.author
%p
  Web Link:
  =@term.web_link
%p
  Category ID:
  =@term.category_id

=link_to 'Edit', edit_term_path(@term)
\|
=link_to 'Back', terms_path

app/views/users/new.html.haml
%h1 New User
.form
= form_for(@user) do |f|
  Name:
  = f.text_field :name
  %br
  Email:
  = f.text_field :email
  %br
  Password:
  = f.password_field :password
  %br
  Password Confirmation:
  = f.password_field :password_confirmation
  %br
  = f.submit